sudo pip3 install  absl-py
sudo pip3 install  asgiref
sudo pip3 install  astunparse
sudo pip3 install  beautifulsoup4
sudo pip3 install  biopython
sudo pip3 install  cachetools
sudo pip3 install  certifi
sudo pip3 install  cffi
sudo pip3 install  chardet
sudo pip3 install  click
sudo pip3 install  cycler
sudo pip3 install  Deprecated
sudo pip3 install  dill
sudo pip3 install  Django
sudo pip3 install  django-googlesearch
sudo pip3 install  dnspython
sudo pip3 install  eventlet
sudo pip3 install  futures
sudo pip3 install  gast
sudo pip3 install  gevent
sudo pip3 install  google-auth
sudo pip3 install  google-auth-oauthlib
sudo pip3 install  google-pasta
sudo pip3 install  greenlet
sudo pip3 install  grpcio
sudo pip3 install  h5py
sudo pip3 install  idna
sudo pip3 install  importlib-metadata
sudo pip3 install  joblib
sudo pip3 install  Keras-Preprocessing
sudo pip3 install  kiwisolver
sudo pip3 install  Markdown
sudo pip3 install  matplotlib
sudo pip3 install  monotonic
sudo pip3 install  mplot
sudo pip3 install  mpmath
sudo pip3 install  mysql
sudo pip3 install  mysqlclient
sudo pip3 install  netifaces
sudo pip3 install  nltk
sudo pip3 install  numpy
sudo pip3 install  oauthlib
sudo pip3 install  opt-einsum
sudo pip3 install  oschmod
sudo pip3 install  pandas
sudo pip3 install  Pillow
sudo pip3 install  protobuf
sudo pip3 install  pyasn1
sudo pip3 install  pyasn1-modules
sudo pip3 install  pycparser
sudo pip3 install  PyGithub
sudo pip3 install  PyJWT
sudo pip3 install  PyMySQL
sudo pip3 install  pyparsing
sudo pip3 install  python-dateutil
sudo pip3 install  python-engineio
sudo pip3 install  python-engineio-client
sudo pip3 install  python-socketio
sudo pip3 install  python-socketio-client
sudo pip3 install  pytz
sudo pip3 install  regex
sudo pip3 install  requests
sudo pip3 install  requests-oauthlib
sudo pip3 install  rsa
sudo pip3 install  scikit-learn
sudo pip3 install  scipy
sudo pip3 install  shortio
sudo pip3 install  sio
sudo pip3 install  six
sudo pip3 install  sklearn
sudo pip3 install  soupsieve
sudo pip3 install  SQLAlchemy
sudo pip3 install  sqlparse
sudo pip3 install  sympy
sudo pip3 install  tensorboard
sudo pip3 install  tensorboard-plugin-wit
sudo pip3 install  tensorflow
sudo pip3 install  tensorflow-estimator
sudo pip3 install  termcolor
sudo pip3 install  threadpoolctl
sudo pip3 install  tkhtmlview
sudo pip3 install  tkinterhtml
sudo pip3 install  tqdm
sudo pip3 install  urllib3
sudo pip3 install  wget
sudo pip3 install  Werkzeug
sudo pip3 install  wrapt
sudo pip3 install  zipp
sudo pip3 install  zope.event
sudo pip3 install  zope.interface
